//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class berbe
    {
        public int id { get; set; }
        public Nullable<int> id_sadnje { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime datum { get; set; }
        public string kolicina { get; set; }
        public Nullable<int> sezona { get; set; }
    
        public virtual sadnje sadnje { get; set; }
        public virtual sezone sezone { get; set; }
    }
}
