//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class berbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public berbe()
        {
            this.prodaje_biljaka = new HashSet<prodaje_biljaka>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_sadnje { get; set; }
        public System.DateTime datum { get; set; }
        public string kolicina { get; set; }
        public Nullable<int> sezona { get; set; }
    
        public virtual sadnje sadnje { get; set; }
        public virtual sezone sezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodaje_biljaka> prodaje_biljaka { get; set; }
    }
}
