//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class gospodarstva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gospodarstva()
        {
            this.mljekomati = new HashSet<mljekomati>();
            this.parcele = new HashSet<parcele>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Morate ispuniti ime.")]
        [StringLength(40, MinimumLength =2)]
        public string ime { get; set; }

        [Required(ErrorMessage = "Morate ispuniti prezime.")]
        [StringLength(40, MinimumLength = 2)]
        public string prezime { get; set; }

        [Required(ErrorMessage = "Morate ispuniti kontakt podatke.")]
        [DataType(DataType.PhoneNumber)]
        public string kontakt { get; set; }

        public Nullable<int> id_zadruge { get; set; }
        [Required(ErrorMessage = "Morate ispuniti email.")]
        [StringLength(70)]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Required(ErrorMessage = "Morate ispuniti lozinku.")]
        [DataType(DataType.Password)]
        public string lozinka { get; set; }
    
        public virtual zadruge zadruge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mljekomati> mljekomati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parcele> parcele { get; set; }
    }
}
