//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class mljekomati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mljekomati()
        {
            this.punjenje_mljekomata = new HashSet<punjenje_mljekomata>();
            this.servisi_mljekomata = new HashSet<servisi_mljekomata>();
        }
    
        public int id { get; set; }
        public int id_korisnika { get; set; }
        [Required]
        public string lokacija { get; set; }
        [Required]
        public int kapacitet { get; set; }
    
        public virtual gospodarstva gospodarstva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<punjenje_mljekomata> punjenje_mljekomata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servisi_mljekomata> servisi_mljekomata { get; set; }
    }
}
