//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class oranice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oranice()
        {
            this.sadnje = new HashSet<sadnje>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_parcele { get; set; }
        [Required]
        public string naziv { get; set; }
        [Required]
        public string dimenzije { get; set; }
        public Nullable<int> stanje_tla { get; set; }
        public Nullable<int> vrsta_tla { get; set; }
    
        public virtual stanje_tla stanje_tla1 { get; set; }
        public virtual parcele parcele { get; set; }
        public virtual vrste_tla vrste_tla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sadnje> sadnje { get; set; }
    }
}
