//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodaje_sirovina
    {
        public int id { get; set; }
        public int id_sirovine { get; set; }
        public int kolicina { get; set; }
        public System.DateTime datum { get; set; }
        public string profit { get; set; }
    
        public virtual sirovine sirovine { get; set; }
    }
}
