//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodaje_biljaka
    {
        public int id { get; set; }
        public Nullable<int> id_biljke { get; set; }
        public string kolicina { get; set; }
        public string profit { get; set; }
    
        public virtual biljke biljke { get; set; }
    }
}
