//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class punjenje_mljekomata
    {
        public int id { get; set; }
        public int id_mljekomata { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime datum { get; set; }
        public Nullable<int> troskovi { get; set; }
        public int profit { get; set; }
        public string preostala_kolicina { get; set; }
    
        public virtual mljekomati mljekomati { get; set; }
    }
}
