//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class radnje_oranica
    {
        public int id { get; set; }
        public Nullable<int> id_tip_radnje { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> id_oranice { get; set; }
    
        public virtual oranice oranice { get; set; }
        public virtual tip_radnje_oranice tip_radnje_oranice { get; set; }
    }
}
