//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class servisi_mljekomata
    {
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public int troskovi { get; set; }
        public Nullable<int> id_mljekomata { get; set; }
    
        public virtual mljekomati mljekomati { get; set; }
    }
}
