//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class strojevi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public strojevi()
        {
            this.radnje_stroja = new HashSet<radnje_stroja>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public System.DateTime datum_kupovine { get; set; }
        public string trosak { get; set; }
        public string vrijednost { get; set; }
        public Nullable<int> id_parcele { get; set; }
    
        public virtual parcele parcele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radnje_stroja> radnje_stroja { get; set; }
    }
}
